### ISSUE TITLE
MSVC : 'and'/'not' : undeclared identifier (error C2065)

### ISSUE THREAD

**Issue by nyue** [PixarAnimationStudios/OpenSubdiv#779] opened 2016-01-29 04:54 UTC
I am able to build the OpenSubdiv 3.0.3 library (no graphics, just the CPU evaluator stuff) on Windows (VS 2012)

When I attempt to use it in a project, I get the 'and' and 'not' keyword undefined.

I tried looking at the CMakeLists.txt files in the github source but could not find any obvious way to tell MSVC to honor the C++ standard keywords.

Cheers

**Comment by c64kernal** [comment] 2016-01-29 06:14
Hi Nicholas,

In the CMakeLists.txt file at the root of the project is a bunch of defines that are meant to solve this problem.  This is super hacky and we should clean this up.  Alternative tokens are provided by the iso646.h header and we should be using that instead.  The /Za option which disables MSVC's language extensions and allow it to support alternative tokens natively is not at all practical.

**Comment by thomthom** [comment] 2016-02-02 21:26
I ran into the same issue when making a VS project using OpenSubdiv. I worked around it by including `iso646.h` before including the OSD headers.

However, I meant to open a ticket on this myself. While I did find the comments in the `CMakeLists.txt` file a couple of days ago describing the issue, I wanted to suggest that either OSD include `iso646.h` or that perhaps the `and`, `or` and `not` keywords where refactored to the more common operators. 

I was confused at first when I ran into this - because the VS solution Cmake generates builds fine, but my own failed when I used the includes. I didn't realize that was these special project properties defined to address this VS compiler limitation.

By the way - is this project using any particular code style guide?

**Comment by thomthom** [comment] 2016-02-02 22:18
I'm also wondering if there are other project compiler flags that might benefit from being defined in the source?

```
                    # Make sure WinDef.h does not define min and max macros which
                    # will conflict with std::min() and std::max().
                    /DNOMINMAX

                    # Make sure the constants in <math.h> get defined.
                    /D_USE_MATH_DEFINES
```

**Comment by thomthom** [comment] 2016-02-15 15:07
What is the desired fix for this issue? Ensure `iso646.h` is included in the files that use these keywords? Or refactor to use `&&` and `||` etc instead?

**Comment by c64kernal** [comment] 2016-02-16 06:07
Hi Thomas, I think the general preference is to use the iso646.h header -- however there was some concern that it may not be supported on older compilers that we'd still like to support.

As far as general coding style, the documentation simply says: inspired by the Google style guide (http://google-styleguide.googlecode.com/svn/trunk/cppguide.xml)

**Comment by thomthom** [comment] 2016-02-16 10:02
Any list of these compliers? Wondering - if there's a way for contributors to tests this so they/we can submit patches for it. I wouldn't mind taking a stab at it as it would simplify my projects since I work with VS all the time and I keep running into this.

**Comment by c64kernal** [comment] 2016-02-17 18:58
Hi Thomas, we've discussed this again and are all in agreement that removing the alternative tokens altogether for consistency and compatibility is the best choice.

Is that something you were planning to do?

**Comment by thomthom** [comment] 2016-02-17 22:24
I can take a stab at it. I'd be happy to contribute back with something. The OSD math is a bit beyond me but I can poke into this.

**Comment by thomthom** [comment] 2016-02-19 21:43
I had a look into this. Started with minimal builds and then incrementally enabled configs. Realizing this is a much larger change than first expected.

Current working branch is here:
https://github.com/thomthom/OpenSubdiv/tree/dev-iso646-fix

Current config that I'm on:
```
cmake ^
  -G "Visual Studio 12 2013 Win64" ^
  -D GLEW_LOCATION="C:\Users\Thomas\Libraries\glew" ^
  -D GLFW_LOCATION="C:\Users\Thomas\Libraries\glfw" ^
  -D NO_DOC=1 ^
  -D NO_MAYA=1 ^
  -D NO_PTEX=1 ^
  -D NO_OMP=1 ^
  -D NO_TBB=1 ^
  -D NO_CUDA=1 ^
  -D NO_OPENCL=1 ^
  -D NO_CLEW=1 ^
  ..
```

Had issues with PTex - after getting Zlib I get some errors still. So I set that aside for the moment.
I also set CUDA aside as it was quite a large SDK that wanted to update my graphic drivers - don't want to mess with that right now.
But what's more is that I realize that the Maya SDK require registering to get access to. 

Seeing how many small changes are being made for this refactor there'd have to be a very careful and code review to catch mistakes.

What I wanted to check in with was whether someone with any of the configs I haven't got set up would be willing to take a stab at? Otherwise it might be a while before I can complete this - and then the source might be too out of date given how many tiny changes scattered all over the source this requires to complete.

Alternately, back out the Cmake config that define the macro's so that smaller changes can be checked in without breaking VS builds. Then remove the macros at the end when everything has been refactored.

**Comment by manuelk** [comment] 2016-02-19 22:53
> Had issues with PTex - after getting Zlib I get some errors still.

There have been some code churn on the ptex side:
- i have been hunting down an MSVC bug reading ptex files (thanks Brent for the quick patch) 
- i have also fixed some issues with the CMake build (change pulled yesterday)
On the OSD side:
- i have a fix for the ptex name space changes that i am going to submit shortly

All combined, this should help your problems quite a bit. After that, if i have a bit of spare time i'll try to push on the CMake build of ptex to move zlib as a recursive dependent git module. I am hoping to figure out some kind of solution to link statically or somehow remove the need to constantly copy the dll's in the bin directories (my kingdom for Linux...).

Finally, I have another (somewhat ugly) fix in-flight to deal with 3-channel ptex formats and the lack of DXGI 3-channel formats.

**Comment by thomthom** [comment] 2016-02-19 23:04
My issue is probably that I configured the Ptex build wrong. I'm getting linker errors which I think relate to zlib.

I generated the Ptex solution using:

`cmake -G "Visual Studio 12 2013 Win64" -DZLIB_INCLUDE_DIR=C:\Users\Thomas\Libraries\zlib-1.2.8\include -DZLIB_LIBRARY=C:\Users\Thomas\Libraries\zlib-1.2.8\lib\zdll.lib`

Didn't look too close into what was the cause.

Having the dependencies as sub-modules would be great.
You looking to build zlib as a static lib instead of DLL?

**Comment by c64kernal** [comment] 2016-02-20 18:52
Hi Thomas, in terms of strategy for landing this kind of change, I think you'd have to do library by library, then pull out the macros like you suggested.  Small changes are much easier to code-review for typos.  The few new cases that may be introduced in the meantime can be fixed along with the removing of the macros.  Thanks for taking a stab at this!

**Comment by davidgyu** [comment] 2016-06-25 21:56
Alright. With PR #970 #807 #808 and #811 we should have all of the necessary source changes.

I had to roll back to VS2013 to test everything since the latest CUDA release (8.0 RC) doesn't support VS2015 Update 2.

**Comment by davidgyu** [comment] 2016-07-08 06:36
Closing. Thanks again to all who contributed to this fix!

**Closed by davidgyu** 2016-07-08 06:36 UTC

**Comment by thomthom** [comment] 2016-07-08 07:49
Thank you so much for doing this. Another thing I can simplify in my project. :)

**Comment by thomthom** [comment] 2016-10-15 12:50
I just updated my project to use 3.1 RC1 on master, and I remove my `#include <ciso646>` include that I previously had to use to use the OSD headers, but I'm getting errors that refer to these keywords:

![image](https://cloud.githubusercontent.com/assets/192418/19410225/9368041c-92e6-11e6-9522-fb4e9f25b635.png)

**Comment by barfowl** [comment] 2016-10-15 20:29
I didn't see your Edit until I came here to see the issue, but yes, it looks like you're not building with the most recent code.  The line numbers indicate they don't include other recent updates to these files, e.g. the line causing the latter error is now:

    173     bool hasSmoothBoundaries() const { return ! _hasLinearBoundaries; }

**Comment by thomthom** [comment] 2016-10-15 21:39
Yea, I was using a new git client and the UI confused me. Once I managed to ensure I was on the right commit everything was fine. I could finally get rid of ciso646 include :)
