### ISSUE TITLE
Unreferenced Glew externals in gl_common etc..

### ISSUE THREAD

**Issue by davidguk2015** [PixarAnimationStudios/OpenSubdiv#542] opened 2015-05-28 14:59 UTC
Hi guys,

I'm currently stepping through the process of getting OpenSubdivs to compile in VS 2010.  I wanted to include and build EVERYTHING from the library and so have had to jump through a few hoops so far, but now at a point where i'm stuck..

When building dxPtexViewer i'm getting a bunch of unreferenced externals relating to glew from inside gl_framebuffer, gl_hud, and gl_common.  These are all inside the examples_common_obj subproject which actually builds and creates the obj files without any errors ( although i had to clear up a couple of minor problems which i'll mention at the end ).  But when building dxPtexViewer itself these errors are coming up..

Glew is included in the properties and dependencies etcand seems to be recognised okay from what i can see.  I think maybe there's an include missing in the code or headers somewhere or something obvious, but i can't figure it out ( have tried a few things ).

Here are a couple of select errors from the dxPtexViewer build:
```
1>gl_framebuffer.obj : error LNK2019: unresolved external symbol __glewUseProgram referenced in function "public: virtual void __cdecl GLFrameBuffer::ApplyImageShader(void)" (?ApplyImageShader@GLFrameBuffer@@UEAAXXZ)

1>gl_framebuffer.obj : error LNK2019: unresolved external symbol __glewActiveTexture referenced in function "public: virtual void __cdecl GLFrameBuffer::ApplyImageShader(void)" (?ApplyImageShader@GLFrameBuffer@@UEAAXXZ)

1>gl_hud.obj : error LNK2019: unresolved external symbol __glewGetAttribLocation referenced in function "public: virtual void __cdecl GLhud::Init(int,int,int,int)" (?Init@GLhud@@UEAAXHHHH@Z)

1>gl_common.obj : error LNK2019: unresolved external symbol __glewGetShaderiv referenced in function "unsigned int __cdecl compileShader(unsigned int,char const *)" (?compileShader@@YAIIPEBD@Z)
```
Here's a screengrab of hovering over one of the offending lines in VisualStudio:

![screengrab](http://i57.tinypic.com/152gbde.jpg)

Any help or suggestions with that would be much appreciated.

A couple of notes regards what i've found so far getting things up in running so far in Windows 7 Pro 64-bit with Cmake building 64-bit target projects, and working in VisualStudio 2010 with recently installed Cuda 7.0 SDK:

Inside osg_gpu_obj i was getting undefined for the following:
```
		clCreateFromGLBuffer
		clEnqueueAcquireGLObjects
		clEnqueueReleaseGLObjects
```
And had to add the following include to get the build on that to work:
		Inside the file clGLVertexBuffer.cpp:
```
		#include "CL\cl_gl.h"
```
VisualStudio 2010 Express version was passing X86 to NVCC and i think trying to use CL.exe within the wrong vsbin folder ( rather than using the AMD64 subfolder ) and no matter what i tried i could not find a fix for this so switched over to VS 2010 Pro.

Next thing was building examples_common_obj:
```
		1>gl_framebuffer.cpp(340): error C3861: 'snprintf': identifier not found
```
This is because afaik VS doesn't support C99 standard and so the fix was to replace snprintf with sprintf_s and include <stdio.h>.  I think C++ 11 in later versions of VS possibly support it..

Then again inside gl_framebuffer.cpp there was the following:
```
		1>gl_framebuffer.cpp(360): error C2057: expected constant expression
		1>gl_framebuffer.cpp(360): error C2466: cannot allocate an array of constant size 0
		1>gl_framebuffer.cpp(360): error C2133: 'rows_ptr' : unknown size
```
And so i replace the line png_bytep* rows_ptr [ height ] with the following:
```
				png_bytep* rows_ptr;
				rows_ptr = (png_bytep*) malloc(height*sizeof(png_bytep));
```
And that seemed to work.

There was quite a lot of other fumbling about getting it to this point especially regards trying to hack VS Express into submission, i've been at this for days :)  Would be nice to include mention that the png lib etc is also required on the readme and perhaps reference which versions of libraries were used and possibly do a test build on a windows/msvc platform to find out what issues are there..

Anyway, thanks for doing such great work guys and any help with my current problem is greatly appreciated!

**Comment by jcowles** [comment] 2015-05-29 03:23
Hi David,

What version of the code are you building? Is it the current "dev" or "master" branch? We're on the verge of 3.0 release so there's a *lot* of code churn in dev currently.

Missing symbols indicate a problem at link time, which means maybe VS is not finding the GLEW libs.

We build after every merge on OSX, Windows, and Linux using clang, gcc, icc and VisualStudio, so everything /should/ be compiling.

If you give us steps, we would be happy to try to reproduce the issues you are hitting and try to help you through it!

**Comment by davidguk2015** [comment] 2015-05-29 08:45
Thanks a lot for the quick reply -

It's the master branch i've used.  What i'll do is try out the dev branch in the meantime as i can see there is a lot going on in there..

I kinda figured Glew was linking ok because as per the little screengrab, when i hover over the offending code with the mouse it does look like it gets the reference to glew ie the little infobox that pops up reading ''''#define glActiveTexture GLEW_GET_FUN(__glewActiveTexture)''''.  This could be my lack of experience with VS and C++ however..

**Comment by davidguk2015** [comment] 2015-06-01 08:54
Hiya,

I'm still getting a bunch of Glew related errors and stumped as to how to get this working.  I really don't want to take up anybody's time, but on the off chance someone might have some idea where i'm going wrong i would appreciate it.

Here's a grab of the GLEW entries in the Cmake GUI:

![Glew Cmake](http://i57.tinypic.com/30k7vvd.jpg)

Again, the examples common stuff builds fine ( after some tweaking ) but when building dxPtexViewer throws a bunch of glew related errors.  Here's the errors i'm getting:

````
1>ClCompile:
1>  dxPtexViewer.cpp
1>LINK : warning LNK4044: unrecognized option '/openmp'; ignored
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewDeleteProgram referenced in function "protected: void __cdecl GLFrameBuffer::setProgram(unsigned int)" (?setProgram@GLFrameBuffer@@IEAAXI@Z)
1>glHud.obj : error LNK2001: unresolved external symbol __glewDeleteProgram
1>glShaderCache.obj : error LNK2001: unresolved external symbol __glewDeleteProgram
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewDeleteBuffers referenced in function "protected: virtual __cdecl GLFrameBuffer::~GLFrameBuffer(void)" (??1GLFrameBuffer@@MEAA@XZ)
1>glHud.obj : error LNK2001: unresolved external symbol __glewDeleteBuffers
1>glPtexMipmapTexture.obj : error LNK2001: unresolved external symbol __glewDeleteBuffers
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewDeleteVertexArrays referenced in function "protected: virtual __cdecl GLFrameBuffer::~GLFrameBuffer(void)" (??1GLFrameBuffer@@MEAA@XZ)
1>glHud.obj : error LNK2001: unresolved external symbol __glewDeleteVertexArrays
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewDeleteFramebuffers referenced in function "protected: virtual __cdecl GLFrameBuffer::~GLFrameBuffer(void)" (??1GLFrameBuffer@@MEAA@XZ)
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewDrawBuffers referenced in function "public: virtual void __cdecl GLFrameBuffer::Bind(void)const " (?Bind@GLFrameBuffer@@UEBAXXZ)
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewBindFramebuffer referenced in function "public: virtual void __cdecl GLFrameBuffer::Bind(void)const " (?Bind@GLFrameBuffer@@UEBAXXZ)
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewBindVertexArray referenced in function "public: virtual void __cdecl GLFrameBuffer::ApplyImageShader(void)" (?ApplyImageShader@GLFrameBuffer@@UEAAXXZ)
1>glHud.obj : error LNK2001: unresolved external symbol __glewBindVertexArray
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewActiveTexture referenced in function "public: virtual void __cdecl GLFrameBuffer::ApplyImageShader(void)" (?ApplyImageShader@GLFrameBuffer@@UEAAXXZ)
1>glHud.obj : error LNK2001: unresolved external symbol __glewActiveTexture
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewUseProgram referenced in function "public: virtual void __cdecl GLFrameBuffer::ApplyImageShader(void)" (?ApplyImageShader@GLFrameBuffer@@UEAAXXZ)
1>glHud.obj : error LNK2001: unresolved external symbol __glewUseProgram
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewCheckFramebufferStatus referenced in function "public: virtual void __cdecl GLFrameBuffer::Reshape(int,int)" (?Reshape@GLFrameBuffer@@UEAAXHH@Z)
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewFramebufferTexture2D referenced in function "public: virtual void __cdecl GLFrameBuffer::Reshape(int,int)" (?Reshape@GLFrameBuffer@@UEAAXHH@Z)
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewProgramUniform1f referenced in function "public: void __cdecl SSAOGLFrameBuffer::SetRadius(float)" (?SetRadius@SSAOGLFrameBuffer@@QEAAXM@Z)
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewUniform1i referenced in function "protected: unsigned int __cdecl GLFrameBuffer::compileProgram(char const *,char const *)" (?compileProgram@GLFrameBuffer@@IEAAIPEBD0@Z)
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewProgramUniform1i referenced in function "protected: unsigned int __cdecl GLFrameBuffer::compileProgram(char const *,char const *)" (?compileProgram@GLFrameBuffer@@IEAAIPEBD0@Z)
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewGetUniformLocation referenced in function "protected: unsigned int __cdecl GLFrameBuffer::compileProgram(char const *,char const *)" (?compileProgram@GLFrameBuffer@@IEAAIPEBD0@Z)
1>glHud.obj : error LNK2001: unresolved external symbol __glewGetUniformLocation
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewGetProgramInfoLog referenced in function "protected: unsigned int __cdecl GLFrameBuffer::compileProgram(char const *,char const *)" (?compileProgram@GLFrameBuffer@@IEAAIPEBD0@Z)
1>glHud.obj : error LNK2001: unresolved external symbol __glewGetProgramInfoLog
1>glShaderCache.obj : error LNK2001: unresolved external symbol __glewGetProgramInfoLog
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewGetProgramiv referenced in function "protected: unsigned int __cdecl GLFrameBuffer::compileProgram(char const *,char const *)" (?compileProgram@GLFrameBuffer@@IEAAIPEBD0@Z)
1>glHud.obj : error LNK2001: unresolved external symbol __glewGetProgramiv
1>glShaderCache.obj : error LNK2001: unresolved external symbol __glewGetProgramiv
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewDeleteShader referenced in function "protected: unsigned int __cdecl GLFrameBuffer::compileProgram(char const *,char const *)" (?compileProgram@GLFrameBuffer@@IEAAIPEBD0@Z)
1>glHud.obj : error LNK2001: unresolved external symbol __glewDeleteShader
1>glShaderCache.obj : error LNK2001: unresolved external symbol __glewDeleteShader
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewLinkProgram referenced in function "protected: unsigned int __cdecl GLFrameBuffer::compileProgram(char const *,char const *)" (?compileProgram@GLFrameBuffer@@IEAAIPEBD0@Z)
1>glHud.obj : error LNK2001: unresolved external symbol __glewLinkProgram
1>glShaderCache.obj : error LNK2001: unresolved external symbol __glewLinkProgram
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewAttachShader referenced in function "protected: unsigned int __cdecl GLFrameBuffer::compileProgram(char const *,char const *)" (?compileProgram@GLFrameBuffer@@IEAAIPEBD0@Z)
1>glHud.obj : error LNK2001: unresolved external symbol __glewAttachShader
1>glShaderCache.obj : error LNK2001: unresolved external symbol __glewAttachShader
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewCreateProgram referenced in function "protected: unsigned int __cdecl GLFrameBuffer::compileProgram(char const *,char const *)" (?compileProgram@GLFrameBuffer@@IEAAIPEBD0@Z)
1>glHud.obj : error LNK2001: unresolved external symbol __glewCreateProgram
1>glShaderCache.obj : error LNK2001: unresolved external symbol __glewCreateProgram
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewGenFramebuffers referenced in function "public: virtual void __cdecl GLFrameBuffer::Init(int,int)" (?Init@GLFrameBuffer@@UEAAXHH@Z)
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewVertexAttribPointer referenced in function "public: virtual void __cdecl GLFrameBuffer::Init(int,int)" (?Init@GLFrameBuffer@@UEAAXHH@Z)
1>glHud.obj : error LNK2001: unresolved external symbol __glewVertexAttribPointer
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewEnableVertexAttribArray referenced in function "public: virtual void __cdecl GLFrameBuffer::Init(int,int)" (?Init@GLFrameBuffer@@UEAAXHH@Z)
1>glHud.obj : error LNK2001: unresolved external symbol __glewEnableVertexAttribArray
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewBufferData referenced in function "public: virtual void __cdecl GLFrameBuffer::Init(int,int)" (?Init@GLFrameBuffer@@UEAAXHH@Z)
1>glHud.obj : error LNK2001: unresolved external symbol __glewBufferData
1>glPtexMipmapTexture.obj : error LNK2001: unresolved external symbol __glewBufferData
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewBindBuffer referenced in function "public: virtual void __cdecl GLFrameBuffer::Init(int,int)" (?Init@GLFrameBuffer@@UEAAXHH@Z)
1>glHud.obj : error LNK2001: unresolved external symbol __glewBindBuffer
1>glPtexMipmapTexture.obj : error LNK2001: unresolved external symbol __glewBindBuffer
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewGenBuffers referenced in function "public: virtual void __cdecl GLFrameBuffer::Init(int,int)" (?Init@GLFrameBuffer@@UEAAXHH@Z)
1>glHud.obj : error LNK2001: unresolved external symbol __glewGenBuffers
1>glPtexMipmapTexture.obj : error LNK2001: unresolved external symbol __glewGenBuffers
1>glFramebuffer.obj : error LNK2019: unresolved external symbol __glewGenVertexArrays referenced in function "public: virtual void __cdecl GLFrameBuffer::Init(int,int)" (?Init@GLFrameBuffer@@UEAAXHH@Z)
1>glHud.obj : error LNK2001: unresolved external symbol __glewGenVertexArrays
1>glHud.obj : error LNK2019: unresolved external symbol __glewUniformMatrix4fv referenced in function "public: virtual bool __cdecl GLhud::Flush(void)" (?Flush@GLhud@@UEAA_NXZ)
1>glHud.obj : error LNK2019: unresolved external symbol __glewGetAttribLocation referenced in function "public: virtual void __cdecl GLhud::Init(int,int,int,int)" (?Init@GLhud@@UEAAXHHHH@Z)
1>glUtils.obj : error LNK2019: unresolved external symbol glfwWindowHint referenced in function "void __cdecl GLUtils::SetMinimumGLVersion(int,char * *)" (?SetMinimumGLVersion@GLUtils@@YAXHPEAPEAD@Z)
1>glUtils.obj : error LNK2019: unresolved external symbol __glewGetShaderInfoLog referenced in function "unsigned int __cdecl GLUtils::CompileShader(unsigned int,char const *)" (?CompileShader@GLUtils@@YAIIPEBD@Z)
1>glShaderCache.obj : error LNK2001: unresolved external symbol __glewGetShaderInfoLog
1>glUtils.obj : error LNK2019: unresolved external symbol __glewGetShaderiv referenced in function "unsigned int __cdecl GLUtils::CompileShader(unsigned int,char const *)" (?CompileShader@GLUtils@@YAIIPEBD@Z)
1>glShaderCache.obj : error LNK2001: unresolved external symbol __glewGetShaderiv
1>glUtils.obj : error LNK2019: unresolved external symbol __glewCompileShader referenced in function "unsigned int __cdecl GLUtils::CompileShader(unsigned int,char const *)" (?CompileShader@GLUtils@@YAIIPEBD@Z)
1>glShaderCache.obj : error LNK2001: unresolved external symbol __glewCompileShader
1>glUtils.obj : error LNK2019: unresolved external symbol __glewShaderSource referenced in function "unsigned int __cdecl GLUtils::CompileShader(unsigned int,char const *)" (?CompileShader@GLUtils@@YAIIPEBD@Z)
1>glShaderCache.obj : error LNK2001: unresolved external symbol __glewShaderSource
1>glUtils.obj : error LNK2019: unresolved external symbol __glewCreateShader referenced in function "unsigned int __cdecl GLUtils::CompileShader(unsigned int,char const *)" (?CompileShader@GLUtils@@YAIIPEBD@Z)
1>glShaderCache.obj : error LNK2001: unresolved external symbol __glewCreateShader
1>glUtils.obj : error LNK2019: unresolved external symbol glewIsSupported referenced in function "bool __cdecl GLUtils::SupportsAdaptiveTessellation(void)" (?SupportsAdaptiveTessellation@GLUtils@@YA_NXZ)
1>glUtils.obj : error LNK2019: unresolved external symbol __GLEW_VERSION_4_1 referenced in function "bool __cdecl GLUtils::GL_ARBSeparateShaderObjectsOrGL_VERSION_4_1(void)" (?GL_ARBSeparateShaderObjectsOrGL_VERSION_4_1@GLUtils@@YA_NXZ)
1>glUtils.obj : error LNK2019: unresolved external symbol __GLEW_VERSION_4_3 referenced in function "bool __cdecl GLUtils::GL_ARBComputeShaderOrGL_VERSION_4_3(void)" (?GL_ARBComputeShaderOrGL_VERSION_4_3@GLUtils@@YA_NXZ)
1>glShaderCache.obj : error LNK2019: unresolved external symbol __glewGetAttachedShaders referenced in function "public: bool __cdecl GLDrawConfig::Link(void)" (?Link@GLDrawConfig@@QEAA_NXZ)
1>glPtexMipmapTexture.obj : error LNK2019: unresolved external symbol __glewTexBuffer referenced in function "unsigned int __cdecl genTextureBuffer(unsigned int,__int64,void const *)" (?genTextureBuffer@@YAII_JPEBX@Z)
1>glPtexMipmapTexture.obj : error LNK2019: unresolved external symbol __glewTextureBufferEXT referenced in function "unsigned int __cdecl genTextureBuffer(unsigned int,__int64,void const *)" (?genTextureBuffer@@YAII_JPEBX@Z)
1>glPtexMipmapTexture.obj : error LNK2019: unresolved external symbol __glewNamedBufferDataEXT referenced in function "unsigned int __cdecl genTextureBuffer(unsigned int,__int64,void const *)" (?genTextureBuffer@@YAII_JPEBX@Z)
1>glPtexMipmapTexture.obj : error LNK2019: unresolved external symbol __glewTexImage3D referenced in function "public: static class GLPtexMipmapTexture * __cdecl GLPtexMipmapTexture::Create(class PtexTexture *,int,unsigned __int64)" (?Create@GLPtexMipmapTexture@@SAPEAV1@PEAVPtexTexture@@H_K@Z)
1>G:\OSD\OpenSubdiv-dev\OpenSubdiv-dev\build\bin\Release\dxPtexViewer.exe : fatal error LNK1120: 44 unresolved externals
1>
1>Build FAILED.
````

I've tried inserting the paths to glew into the properties, adding in includes etc to no avail..

Just to add - the above GLEW includes shown on the Cmake GUI use a newer version of GLEW ( 1.12 ) i also tried basically replacing all the files ( but kept the paths ) with older versions ( 1.9 ) in case it helped, which it didn't.

Any ideas would be much appreciated!

**Comment by jcowles** [comment] 2015-06-03 20:51
Looks like you're using GLEW MX (new in 1.2 to support thread safe multiple rendering context), could you try using the standard version instead?

**Comment by davidguk2015** [comment] 2015-06-04 09:33
Thanks jc..  I had tried switching to glew32.lib and that didn't work but switching to glew32s.lib actually did..

I think my final problem now is another unresolved external in glUtils to glfwWindowHint..  It definitely recognises the function in the IDE so i'm assuming another version issue or compile time linking problem..  Thats with glfw3.lib from GLFW 3.1.1 will maybe try another version.  Will get there eventually :)

**Comment by davidguk2015** [comment] 2015-06-04 10:39
I can't get GLFW working for dxPtexViewer as above, have tried everything i can think of really :/

dxViewer is working however..  Damn that is fast!  Superb..

**Comment by davidguk2015** [comment] 2015-06-04 12:47
Ah i figured it out -

I put glfw3.lib including full path to it in the Linker/Input/AdditionalDependencies list for dxPtexViewer..

**Comment by jcowles** [comment] 2015-06-04 18:20
Glad to hear it! Let us know if you hit any other snags.

FYI, we just landed RC1 back into master, it's official.

Closing.

**Closed by jcowles** 2015-06-04 18:20 UTC
