### ISSUE TITLE
OpenSubdiv fails to compile CUDA kernels with CUDA 7.0+

### ISSUE THREAD

**Issue by lukasstockner** [PixarAnimationStudios/OpenSubdiv#751] opened 2015-10-15 14:09 UTC
When building OpenSubdiv with CUDA 7.0, generating the CUDA kernels fails with this message:
```
[ 87%] Building NVCC (Device) object opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/./osd_static_gpu_generated_cudaKernel.cu.o
nvcc fatal   : Value 'compute_11' is not defined for option 'gpu-architecture'
CMake Error at osd_static_gpu_generated_cudaKernel.cu.o.cmake:206 (message):
```
From version 7.0 on, the 1.x compute architectures are no longer supported, so the CMake scripts should probably detect that case and use compute_20 instead.

**Comment by manuelk** [comment] 2016-01-13 19:53
Looking into FindCUDA.cmake it looks like all we would have to do is add something like this to opensubdiv/osd/CMakeLists.txt:295:

```
set(OSD_CUDA_COMPUTE "compute_11")
if ((CUDA_VERSION GREATER 20) or (CUDA_VERSION EQUAL 20))
    set(OSD_CUDA_COMPUTE "compute_20")
endif()
list(APPEND CUDA_NVCC_FLAGS "${OSD_CUDA_COMPUTE}")
```

I'll try to patch in a fix when i get the chance to test this snippet (unless someone else gets to it before i do)

**Comment by opeca64** [comment] 2016-01-23 17:46
Duplicate of #472.  If you patch it let me know.

**Closed** 2016-09-30 15:56 UTC
Labels: bug, build, osd
