### ISSUE TITLE
Tutorial : bfr - meshLoader.h and objWriter.h duplicated ?

### ISSUE THREAD

**Issue by nyue** [PixarAnimationStudios/OpenSubdiv#1280] opened 2022-10-04 18:11 UTC
It seems that the file meshLoader.h and objWriter.h in each of the 9 bfr tutorial are duplicates.

Is there a reason behind this ?

**Comment by barfowl** [comment] 2022-10-06 02:00
Yes, this is intentional. The code in those source files is also duplicated in some of the Far tutorials -- but as part of the single source file in those cases.

With the set of Bfr tutorials we wanted to strip the main source file down so that it focuses on what the tutorial is intended to illustrate (in part since the main source file is imported into the online documentation).

We considered moving the source in those additional files to a common location, but for a variety of reasons chose not to. One of those reasons is that keeping that code in the same source directory makes it easier to see what it is doing and modify it for exploratory or debugging purposes (which I have done on numerous occasions).  As tutorials, relying on too much code hidden somewhere obscure starts to work against the goal that they be easily understood at a glance.

**Comment by barfowl** [comment] 2022-10-07 02:59
Having answered this, there's probably not much discussion here so I'll close this issue.

We may move the noted source files into a common place at some point in future, but what that location would be warrants more discussion in addition to the standards for putting something there. We currently have regression/common (sometimes used by examples), examples/common (sometimes used by regression tests) and don't want to add a new tutorials/common to make matters worse.

**Closed as completed by barfowl** 2022-10-07 02:59 UTC
