### ISSUE TITLE
Why does my PatchTable have so many patches?

### ISSUE THREAD

**Issue by VadiMysore** [PixarAnimationStudios/OpenSubdiv#1101] opened 2019-05-07 04:45 UTC
Adaptive subdivision in certain cases produces too many b-spline patches.  Let us consider the following case.

**Initial:**

![InitialControlCageAndItsLimitSurface](https://user-images.githubusercontent.com/24560022/57272265-a342ae80-7058-11e9-95cf-1351baac3d45.jpg)

**Modified:**

![ModifiedControlCageAndItsLimitSurface](https://user-images.githubusercontent.com/24560022/57272296-c1a8aa00-7058-11e9-9068-e3357830f62a.jpg)

As you see, there is an explosion in the number of b-spline patches created with a slight modification to the original control cage even when the topology remains the same, with the same number of quad faces in the initial control cage. The refinement level is just 1. Why is this so?

Is there a way to reduce this?

**Comment by barfowl** [comment] 2019-05-07 20:37
The PatchTable is based purely on the mesh topology -- it in no way considers vertex positions as part of its construction -- so a simple change to the positions of the control change does not affect it.  As has been pointed out previously, editing positions and providing rapid re-evaluation or drawing for a mesh of fixed topology is the use case that much of OpenSubdiv was designed to support.

If two PatchTables have different numbers of patches, they either are derived from meshes of different topology, or each is constructed using different settings are applied to the common topology (e.g. different level of adaptive refinement).

Based on the topology of the patches I see in the image of the 420 patches, there are many valence-3, which indicates the control cage contained many triangles.  It looks like some process you don't expect is triangulating your mesh after the modification.

**Comment by VadiMysore** [comment] 2019-05-10 04:58
@barfowl - it was a great catch by you! You were spot on when you said the initial cage contained triangles! In fact, the cage comprised only triangles. It was unintended though. I fixed the issue. Thanks for it. 

I have two somewhat related questions.

1. Can we represent a triangle as a "degenerate" quad in the initial control cage? Does  OpenSubdiv even allow this? If it does, what would be the impact on the limiting surface?

2. As I have stated before in other issues, we would ideally like to have one limiting b-spline patch per initial control cage face. Since this is currently not possible in OpenSubdiv, how about manually combining all the patches on a per face basis, provided that they are all G2 continuous? Do you see any issues with this? I think OpenSubdiv has enough information to collect all the limiting surface patches on a per initial control cage face even if the faces are non-quads. Is that right?

Thanks!

**Comment by jtran56** [comment] 2019-05-17 19:12
Filed as internal issue #OSD-288.

**Comment by barfowl** [comment] 2019-05-20 22:23
Regarding (1), by a "degenerate" quad are you referring a geometrically degenerate quad, i.e. a quad defined by four unique vertices {A, B, C, D} where two control point values may be coincident, or a topologically degenerate quad defined by three vertices {A, B, B, C} containing a degenerate edge?

The former is easily accommodated as making two control point values doesn't affect the construction of the patches.  The effect is the same as making two control points of a B-Spline patch coincident.

The latter use of a degenerate edge makes the topology of the mesh non-manifold, which makes the mesh potentially non-portable as many tools will not support this condition.  OpenSubdiv is robust given a mesh with any topology.  What happens in the case of a degenerate edge on a quad {A, B, B, C} depends on the topology around that vertex B.  It may create a sharp cusp on the limit surface or it may remain smooth under some conditions.  OpenSubdiv supports non-manifold topology as it often occurs transitionally between modelling operations but it is not recommended and there are no guarantees on the quality of the limit surface (as of version 3.3, cracks may sometimes appear).

As for (2), yes, OpenSubdiv provides enough information to collect patches associated with a face of the control cage. The Far::PatchParam class provides information about the base face from which the patch was generated (see Far::PatchParam::GetFaceId()).  If your mesh is all quads, this is trivially the base face.  If you do have non-quads in the base mesh, then an unfortunate level of indirection is introduced to the indexing and you will be forced to make use Far::PtexIndices to identify the base face.

You can also use a Far::PatchMap to identify the patches associated with a given base face -- especially if you are only subdividing one level.  Again, if you have non-quads, then you have to deal with these irregular faces specially -- dealing with the quad faces that result after one level of subdivision.  The PatchMap requires use of the previously mentioned PtexIndices.

As for "manually combining all the patches", the B-Spline patches that are generated will not always be at the same level and even when at the same level, they will not always overlap by three control point rows as may be expected, especially if extra-ordinary vertices were not isolated.  If you want to combine them into a piecewise surface, then converting all to Bezier form (cubic B-Spline with triple knots) with shared boundaries will probably simplify the process.

**Comment by VadiMysore** [comment] 2019-05-24 08:12
@barfowl - thanks for the feedback.

**Triangles as quads** - the idea was just a ploy to present triangles as quads as we will not restrict the users from creating non-quad polygonal faces in a control cage. The following pyramid is an example.

![Pyramid](https://user-images.githubusercontent.com/24560022/58219041-0bd39180-7ccf-11e9-90ac-cbeeb52c547b.JPG)

Since there are three triangular faces and a quad face, the thought was that by presenting the triangles as quads to OpenSubdiv by repeating one of their vertices (does this qualify as a geometrically degenerate quad ?) would get a better looking limiting surface. As far as presenting the control cage data to OpenSubdiv how will the distinction between "geometric degeneracy" and "topological degeneracy" matter? 

Also, we will not be doing the above because we do not want to restrict the users to use only quads to model their control cages. We consider it too restrictive though it is not a good modeling technique for SubD. There can be polygonal faces other than triangles.

**Collecting resulting patches on a per control cage face** - we need this information to name the resulting faces in a consistent way. Because, in CAD models, naming of topological elements is very important for predictable downstream modeling. Keying the resulting patches' names off of their respective control cage faces' in a consistent way is essential for downstream stable modeling.

 I understand that non-quad faces in the control cage can lead to indirect indexing. I did look at your suggestion to use Far::PtexIndices.  I looked at the examples delivered with OpenSubdiv for the usage (OpenSubdiv\examples\glEvalLimit\particles.cpp). It is somewhat confusing to me. Can you please give me a simplified example of extracting all the final level patch faces that correspond to a given base face? By the way, I have been using Far::PatchParam to do his currently. Since this may not work for non-quad base faces, I wanted to know what I should for these cases.

**manually combining all the patches**

I only want to do this after constructing b-spline surfaces for the final level patches. I want to run through all the final level patches on a per base face basis (hence, was the previous question) looking for G2 (or G1) continuity among them and then replacing them with a single approximation. We have enough internal tools to do it. But collecting all the final level patches for a base face is the key, especially when non-quad base faces are possible. 

Also, if you have any paper or technical material related to b-spline to bezier conversion and subsequent combining, can you please cite them?

Thanks!

**Comment by barfowl** [comment] 2019-06-26 01:34
I thought the main remaining question here had since been raised in #1121 (and now recently answered) but I see there were a couple more here that I'll try to address before closing this...

Regarding the "geometric degeneracy" versus "topological degeneracy" question, since it sounds like you won't be trying to emulate triangles with degenerate quads, I will avoid that topic.  It sounds like you don't have an appreciation of the kinds of problems non-manifold meshes can create, so I'm not sure where I would begin.  I will point out that if you try to define a quad with four vertices {A, B, B, C}, some tools will not even allow you to import a mesh with that degenerate edge {B,B} or may modify it by replicating the vertex on import (which can lead to other problems).  Versions of OpenSubdiv prior to 3.0 would simply reject a mesh with such faces.

Regarding technical references for conversions between B-spline and Bezier conversion, that is pretty standard -- any basic text on geometric modelling or an internet search should provide you with plenty to choose from.  In the case of individual bicubic patches, the change of basis is a simple matrix multiplication.

Thanks for raising the other question related to non-quads in #1121.  Since the original issue about "too many patches" has been addressed, this can be closed.

**Closed by barfowl** 2019-06-26 01:34 UTC
