### ISSUE TITLE
Patch factory generated invalid patch when SCHEMA equals SCHEME_BILINEAR

### ISSUE THREAD

**Issue by shengfuintel** [PixarAnimationStudios/OpenSubdiv#733] opened 2015-08-21 21:46 UTC
I created a very simple test case, just one triangle control face in my mesh. It seems when I set SchemaType = OpenSubdiv::Sdc::SCHEME_BILINEAR, the patch indices returned from PatchMap are all zeros ( 4 zero). The following are the modified far/tutorial_6 to show this bug. 

#include <opensubdiv/far/topologyDescriptor.h>
#include <opensubdiv/far/primvarRefiner.h>
#include <opensubdiv/far/patchTableFactory.h>
#include <opensubdiv/far/patchMap.h>
#include <opensubdiv/far/ptexIndices.h>

#include <cassert>
#include <cstdio>
#include <cstring>
#include <cfloat>

using namespace OpenSubdiv;

// pyramid geometry from catmark_pyramid_crease0.h
static int const g_nverts = 3;
static float const g_verts[9] = { 0.0f,  1.0f, 0.0f,
                                   0.0f, 0.0f, 0.0f,
                                   1.0f,  0.0f, 0.0f};

static int const g_vertsperface[1] = { 3};

static int const g_nfaces = 1;
static int const g_faceverts[3] = { 0, 1, 2};

// Creates a Far::TopologyRefiner from the pyramid shape above
static Far::TopologyRefiner * createTopologyRefiner();

//------------------------------------------------------------------------------
// Vertex container implementation.
//
struct Vertex {

    // Minimal required interface ----------------------
    Vertex() { }

    void Clear( void * =0 ) {
         point[0] = point[1] = point[2] = 0.0f;
    }

    void AddWithWeight(Vertex const & src, float weight) {
        point[0] += weight * src.point[0];
        point[1] += weight * src.point[1];
        point[2] += weight * src.point[2];
    }

    float point[3];
};

//------------------------------------------------------------------------------
// Limit frame container implementation -- this interface is not strictly
// required but follows a similar pattern to Vertex.
//
struct LimitFrame {

    void Clear( void * =0 ) {
         point[0] =  point[1] =  point[2] = 0.0f;
        deriv1[0] = deriv1[1] = deriv1[2] = 0.0f;
        deriv2[0] = deriv2[1] = deriv2[2] = 0.0f;
    }

    void AddWithWeight(Vertex const & src,
        float weight, float d1Weight, float d2Weight) {

        point[0] += weight * src.point[0];
        point[1] += weight * src.point[1];
        point[2] += weight * src.point[2];

        deriv1[0] += d1Weight * src.point[0];
        deriv1[1] += d1Weight * src.point[1];
        deriv1[2] += d1Weight * src.point[2];

        deriv2[0] += d2Weight * src.point[0];
        deriv2[1] += d2Weight * src.point[1];
        deriv2[2] += d2Weight * src.point[2];
    }

    float point[3],
          deriv1[3],
          deriv2[3];
};

//------------------------------------------------------------------------------
int main(int, char **) {

    // Generate a FarTopologyRefiner (see far_tutorial_0 for details).
    Far::TopologyRefiner * refiner = createTopologyRefiner();

    // Adaptively refine the topology with an isolation level capped at 3
    // because the sharpest crease in the shape is 3.0f (in g_creaseweights[])
    int maxIsolation = 1;
    refiner->RefineAdaptive(
        Far::TopologyRefiner::AdaptiveOptions(maxIsolation));

    // Generate a set of Far::PatchTable that we will use to evaluate the
    // surface limit
    Far::PatchTableFactory::Options patchOptions;
    patchOptions.endCapType =
        Far::PatchTableFactory::Options::ENDCAP_GREGORY_BASIS;

    Far::PatchTable const * patchTable =
        Far::PatchTableFactory::Create(*refiner, patchOptions);

    // Compute the total number of points we need to evaluate patchtable.
    // we use local points around extraordinary features.
    int nRefinerVertices = refiner->GetNumVerticesTotal();
    int nLocalPoints = patchTable->GetNumLocalPoints();

    // Create a buffer to hold the position of the refined verts and
    // local points, then copy the coarse positions at the beginning.
    std::vector<Vertex> verts(nRefinerVertices + nLocalPoints);
    memcpy(&verts[0], g_verts, g_nverts*3*sizeof(float));

    // Interpolate vertex primvar data : they are the control vertices
    // of the limit patches (see far_tutorial_0 for details)
    Vertex * src = &verts[0];
    for (int level = 1; level <=  refiner->GetMaxLevel(); ++level) {
        Vertex * dst = src + refiner->GetLevel(level-1).GetNumVertices();
        Far::PrimvarRefiner(*refiner).Interpolate(level, src, dst);
        src = dst;
    }

    // Evaluate local points from interpolated vertex primvars.
    patchTable->ComputeLocalPointValues(&verts[0], &verts[nRefinerVertices]);

    // Create a Far::PatchMap to help locating patches in the table
    Far::PatchMap patchmap(*patchTable);

    // Create a Far::PtexIndices to help find indices of ptex faces.
    Far::PtexIndices ptexIndices(*refiner);

    // Generate random samples on each ptex face
    int nsamples = 1,
        nfaces = ptexIndices.GetNumFaces();

    std::vector<LimitFrame> samples(nsamples * nfaces);

    srand( static_cast<int>(2147483647) );

    float pWeights[20], dsWeights[20], dtWeights[20];

    for (int face=0, count=0; face<nfaces; ++face) {

        for (int sample=0; sample<nsamples; ++sample, ++count) {

            float s = (float)rand()/(float)RAND_MAX,
                  t = (float)rand()/(float)RAND_MAX;

            // Locate the patch corresponding to the face ptex idx and (s,t)
            Far::PatchTable::PatchHandle const * handle =
                patchmap.FindPatch(face, s, t);
            assert(handle);

            Far::PatchDescriptor desc = patchTable->GetPatchDescriptor(*handle);
            Far::PatchParam patchParam = patchTable->GetPatchParam(*handle);
            Far::ConstIndexArray indices = patchTable->GetPatchVertices(*handle);   
                    
            // Evaluate the patch weights, identify the CVs and compute the limit frame:
            patchTable->EvaluateBasis(*handle, s, t, pWeights, dsWeights, dtWeights);

            Far::ConstIndexArray cvs = patchTable->GetPatchVertices(*handle);

            LimitFrame & dst = samples[count];
            dst.Clear();
            for (int cv=0; cv < cvs.size(); ++cv) {
                dst.AddWithWeight(verts[cvs[cv]], pWeights[cv], dsWeights[cv], dtWeights[cv]);
            }

        }
    }

    { // Visualization with Maya : print a MEL script that generates particles
      // at the location of the limit vertices

        int nsamples = (int)samples.size();

        printf("file -f -new;\n");

        // Output particle positions for the tangent
        printf("particle -n deriv1 ");
        for (int sample=0; sample<nsamples; ++sample) {
            float const * pos = samples[sample].point;
            printf("-p %f %f %f\n", pos[0], pos[1], pos[2]);
        }
        printf(";\n");
        // Set per-particle direction using the limit tangent (display as 'Streak')
        printf("setAttr \"deriv1.particleRenderType\" 6;\n");
        printf("setAttr \"deriv1.velocity\" -type \"vectorArray\" %d ",nsamples);
        for (int sample=0; sample<nsamples; ++sample) {
            float const * tan1 = samples[sample].deriv1;
            printf("%f %f %f\n", tan1[0], tan1[1], tan1[2]);
        }
        printf(";\n");

        // Output particle positions for the bi-tangent
        printf("particle -n deriv2 ");
        for (int sample=0; sample<nsamples; ++sample) {
            float const * pos = samples[sample].point;
            printf("-p %f %f %f\n", pos[0], pos[1], pos[2]);
        }
        printf(";\n");
        printf("setAttr \"deriv2.particleRenderType\" 6;\n");
        printf("setAttr \"deriv2.velocity\" -type \"vectorArray\" %d ",nsamples);
        for (int sample=0; sample<nsamples; ++sample) {
            float const * tan2 = samples[sample].deriv2;
            printf("%f %f %f\n", tan2[0], tan2[1], tan2[2]);
        }
        printf(";\n");

        // Exercise to the reader : cross tangent & bi-tangent for limit
        // surface normal...

        // Force Maya DAG update to see the result in the viewport
        printf("currentTime -edit `currentTime -q`;\n");
        printf("select deriv1Shape deriv2Shape;\n");
    }

}

//------------------------------------------------------------------------------
static Far::TopologyRefiner *
createTopologyRefiner() {

    typedef Far::TopologyDescriptor Descriptor;

//    Sdc::SchemeType type = OpenSubdiv::Sdc::SCHEME_CATMARK;
    Sdc::SchemeType type = OpenSubdiv::Sdc::SCHEME_BILINEAR;

    Sdc::Options options;
    options.SetVtxBoundaryInterpolation(Sdc::Options::VTX_BOUNDARY_EDGE_AND_CORNER);

    Descriptor desc;
    desc.numVertices = g_nverts;
    desc.numFaces = g_nfaces;
    desc.numVertsPerFace = g_vertsperface;
    desc.vertIndicesPerFace = g_faceverts;

    // Instantiate a FarTopologyRefiner from the descriptor.
    Far::TopologyRefiner * refiner =
        Far::TopologyRefinerFactory<Descriptor>::Create(desc,
            Far::TopologyRefinerFactory<Descriptor>::Options(type, options));

    return refiner;
}

**Comment by barfowl** [comment] 2015-08-27 01:18
Feature adaptive refinement and patches resulting from it are currently only supported for the SchemeType SCHEME_CATMARK.  That is documented in a few places (though perhaps not as well as it could be) and you should be getting runtime errors if doing otherwise.

In particular, you should definitely be seeing a runtime error about the failure of TopologyRefiner::RefineAdaptive(), i.e. from far/topologyRefiner.cpp:

    243 void
    244 TopologyRefiner::RefineAdaptive(AdaptiveOptions options) {
            ...
    256     if (_subdivType != Sdc::SCHEME_CATMARK) {
    257         Error(FAR_RUNTIME_ERROR,
    258             "Cannot apply adaptive refinement -- currently only supported for scheme Catmark.");
    259         return;
    260     }

I haven't dug into this deeper to see what the PatchTableFactory actual does in this case when given the resulting TopologyRefiner, but I don't see any explicit error checking or reporting to help point out that it is not properly supported.  That's something that could be added to help avoid this.

Eventually all schemes will be supported equally, but the current feature-adaptive PatchTableFactory implementation is currently heavily biased to Catmark -- something that will change as it is refactored to support Loop.

**Comment by shengfuintel** [comment] 2015-08-27 05:12
Thanks. If I call RefineUniform, does PatchTable contains valid linear quad patches?

**Comment by shengfuintel** [comment] 2015-08-27 20:28
It seems if doing RefineUniform, patch index table is correct, however, the patch bitfield does not set up correctly.

**Comment by barfowl** [comment] 2015-08-27 20:55
You're way ahead of me...  I just ran a test and I was getting bilinear
patches that I could evaluate but I was concerned that something may not be
set up as expected (e.g. the PatchMap).

The PatchTableFactory takes a completely separate code path when dealing
with uniform refinement.  Regardless of the scheme all patches are created
as quads or tris (if the triangulation option is set).  This was primarily
done for display purposes, not evaluation, so an oversight may well have
gone undetected.

Can you be more specific about "the patch bitfield does not set up
correctly"?  I don't have a lot of time to dig into this right now, so
anything you've already found would be helpful, thanks.

**Comment by shengfuintel** [comment] 2015-08-27 21:13
In feature adaptive subdivision, when I sample a control face, I call the following code to convert UV from control face level to patch level ( or call normalize):

  uniform float frac = getParamFraction(bitField);
  uniform float pu = (uniform float)getU(bitField)*frac;
  uniform float pv = (uniform float)getV(bitField)*frac;
  float s = (u - pu) / frac;
  float t = (v - pv) / frac;

It depends on bit field for each patch is set up correctly, which does not seems the case for uniform subdivision. 

What I try to do is having the same tessellation code for all cases.

**Comment by barfowl** [comment] 2015-08-27 21:33
What version are you using?  The Far::PatchParam::PatchBitfield struct was
deprecated as part of the 3.0 release when the bitfields were expanded to
64-bit.  You should be calling PatchParam::GetParamFraction() et al which
do not take any parameters.  If you have re-implemented part of the code
for use with ISPC, it may be out of date.

I am able to tessellate uniform bilinear patches in the same way as
adaptive Catmark patches using Far::PatchTables:EvaluateBasis(), which is
mapping the (u,v) coordinate of the base face into the appropriate domain
for the patch via the PatchParam.

**Comment by shengfuintel** [comment] 2015-08-27 21:50
I use the version in master branch. I use  Far::PatchParam::field1 in ISPC code to reimplement Normalize function ( copied from patchParam.h ). 

I have a square to test with, for resolution 1, it works, however, for resolution 2, it seems not sampling the appropriate location.

**Comment by shengfuintel** [comment] 2015-08-27 21:50
I will try Far::PatchTables:EvaluateBasis() later.

**Comment by barfowl** [comment] 2015-08-27 22:08
Yes, patches at level 2 don't seem to be working properly -- I was only
testing 1 and I also get incorrect results with level 2.

Not that it fixes the bug, but for Bilinear there is no point refining past
level 1 if you are creating patches for evaluation.  We're already getting
far more patches than necessary having to refine uniformly.

**Comment by shengfuintel** [comment] 2015-08-27 22:19
Sorry, I confused you. What I mean is: I do uniform refine once, but evaluate base face with 3x3 grid sampling point, then I got wrong result. If I do 2x2 grid sampling pint ( basically the quad itself), I got the correct result.

**Comment by barfowl** [comment] 2015-08-28 01:04
That's odd -- I was able to sample the patches arbitrarily at level 1
without incident.

I believe I have found the problem, and it is not the PatchParam (and its
bitfields) at all.  The PatchParams appear to be initialized correctly for
all levels, but for levels > 1 the patch point indices are not correct.
The "levelVertOffset" variable in Far::PatchTableFactory::createUniform()
is not being set/incremented properly when option generateAllLevels is
false (the default).

I'm surprised this isn't a bigger problem with patches from uniform
subdivision and need to investigate more.

There are also multiple ways to fix it, but in the meantime the simplest is
to comment out the following conditional in
PatchTableFactory::createUniform():

686         //if (options.generateAllLevels) {
687             levelVertOffset += refiner.GetLevel(level).GetNumVertices();
                ...
691         //}

If only generating the last level, there should be no need to iterate
through all levels as the current implementation is doing, so I want to
explore eliminating that.

**Comment by shengfuintel** [comment] 2015-08-28 19:37
Just verified patch evaluation for uniform subdivision (level = 1) is working. It is a bug in my ISPC code.

**Comment by barfowl** [comment] 2015-08-28 20:17
I looked into this further and the current indexing behavior is expected
and not a bug.

Apparently when building a PatchTable for uniformly refined patches, the
control vertices for the patches are all considered to be relative to the
last level, and that is the only level for which data buffers are
expected.  This makes sense since the points at intermediate levels have no
use, but is in contrast to adaptive patches whose points are indexed
relative to level 0.

There is a "generateAllLevels" option but that does generate patches for
intermediate levels rather than just indexing relative to all of them.

I'd prefer there be some kind of option so that the indexing can be made
consistent between the two, but that will be an API change and warrant more
review.

In the meantime, the expectation is that for uniform patches, vertex
indices are all relative to the last level and you will need to offset
either your data buffer or the patch indices accordingly.

**Comment by barfowl** [comment] 2015-08-28 21:08
Sorry, that last post was not quite correct...

Apparently the indices for the patch vertices are relative to the last
level but offset by the first level to account for the vertices of the
cage.  If your buffer is just the cage vertices and those of the last
level, this is ideal.  But if you have buffers including intermediate
levels you have to offset into the next-to-last level for the patch
vertices in the last level to be accessed correctly.

Clearly there is some history to this as everything currently using
uniformly refined patches currently works this way.  Hopefully we can get a
new option in place some time in future to make this more flexible and
intuitive...

**Comment by barfowl** [comment] 2015-09-10 00:26
I'm wondering if there is anything more to do here and if we can close this issue...

The fact that the Bilinear scheme is not supported with adaptive-refinement is documented and should be producing runtime error messages as a further alert.  It's not clear that anything more is needed here.

The indexing of vertices in the PatchTable for uniform patches is, granted, non-intuitive, but it is the behavior currently relied upon, does work as expected once understood, and cannot simply be changed.  If used for Bilinear it should be unnecessary to generate patches beyond level 1, and for that case the indexing works as expected -- so hopefully it is not a practical issue for Bilinear.  It has been noted to improve this in future somehow -- likely with an additional option to control vertex indexing.

Does that cover everything raised here?

**Comment by davidgyu** [comment] 2016-09-30 18:56
Closing this in favor of #737 which captures the main residual issue. Thanks!

**Closed by davidgyu** 2016-09-30 18:56 UTC
