### ISSUE TITLE
Build of osd_static_gpu failed (on Windows 10 using Visual Studio 2013 x64)

### ISSUE THREAD

**Issue by huybui** [PixarAnimationStudios/OpenSubdiv#922] opened 2017-01-19 16:01 UTC
There is an error in the CMake-generated file (build\CMakeFiles\osd_static_gpu.dir\osd\osd_static_gpu_generated_cudaKernel.cu.obj.Release.cmake)
at line 81:
`set(CUDA_NVCC_COMPILE_DEFINITIONS "**OPENSUBDIV_VERSION_STRING="3.1.1";NOMINMAX;_**USE_MATH_DEFINES;_CRT_SECURE_NO_WARNINGS;OPENSUBDIV_HAS_OPENGL;GLFW_VERSION_3;OSD_USES_GLEW;OPENSUBDIV_HAS_GLSL_TRANSFORM_FEEDBACK;OPENSUBDIV_HAS_GLSL_COMPUTE;OPENSUBDIV_HAS_OPENCL;OPENSUBDIV_HAS_CLEW;OPENSUBDIV_HAS_CUDA;OPENSUBDIV_HAS_PTEX;PTEX_STATIC;OPENSUBDIV_HAS_DX11SDK") # list (needs to be in quotes to handle spaces properly).`

Below is the output of Visual Studio:

`31>  Building NVCC (Device) object opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/Release/osd_static_gpu_generated_cudaKernel.cu.obj
31>  CMake Warning (dev) at osd_static_gpu_generated_cudaKernel.cu.obj.Release.cmake:81:
31>    Syntax Warning in cmake code at column 63
31>  
31>    Argument not separated from preceding token by whitespace.
31>  This warning is for project developers.  Use -Wno-dev to suppress it.
31>  
31>  -- Removing C:/Workspace/OpenSubdiv/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/Release/osd_static_gpu_generated_cudaKernel.cu.obj
31>  
31>  "C:/Program Files/CMake/bin/cmake.exe" -E remove C:/Workspace/OpenSubdiv/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/Release/osd_static_gpu_generated_cudaKernel.cu.obj
31>  
31>  -- Generating dependency file: C:/Workspace/OpenSubdiv/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/osd_static_gpu_generated_cudaKernel.cu.obj.NVCC-depend
31>  
31>  "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v7.5/bin/nvcc.exe" -M -D__CUDACC__ C:/Workspace/OpenSubdiv/opensubdiv/osd/cudaKernel.cu -o C:/Workspace/OpenSubdiv/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/osd_static_gpu_generated_cudaKernel.cu.obj.NVCC-depend -ccbin "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin" -m64 -DOPENSUBDIV_VERSION_STRING= -D3.1.1\" -DNOMINMAX -D_USE_MATH_DEFINES -D_CRT_SECURE_NO_WARNINGS -DOPENSUBDIV_HAS_OPENGL -DGLFW_VERSION_3 -DOSD_USES_GLEW -DOPENSUBDIV_HAS_GLSL_TRANSFORM_FEEDBACK -DOPENSUBDIV_HAS_GLSL_COMPUTE -DOPENSUBDIV_HAS_OPENCL -DOPENSUBDIV_HAS_CLEW -DOPENSUBDIV_HAS_CUDA -DOPENSUBDIV_HAS_PTEX -DPTEX_STATIC -DOPENSUBDIV_HAS_DX11SDK\" -Xcompiler ,\"/DWIN32\",\"/D_WINDOWS\",\"/W3\",\"/GR\",\"/EHsc\",\"/MD\",\"/O2\",\"/Ob2\",\"/DNDEBUG\" -DNVCC "-IC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v7.5/include" -IC:/Workspace/OpenSubdiv/opensubdiv "-IC:/Program Files/ptex/include" "-IC:/Users/VGI/Documents/Visual Studio 2013/library/glew-1.13.0/include" "-IC:/Program Files (x86)/Windows Kits/8.1/Include/um" "-IC:/Program Files/CLEW/include"
31>  
31>  nvcc fatal   : Stray '"' character
31>  
31>  CMake Error at osd_static_gpu_generated_cudaKernel.cu.obj.Release.cmake:222 (message):
31>    Error generating
31>    C:/Workspace/OpenSubdiv/build/opensubdiv/CMakeFiles/osd_static_gpu.dir/osd/Release/osd_static_gpu_generated_cudaKernel.cu.obj
31>  
31>  
31>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" exited with code 1.`

**Comment by jtran56** [comment] 2017-01-19 18:39
Filed as internal issue #142048.

**Comment by davidgyu** [comment] 2017-01-20 02:26
Which version of cmake are you using?

I haven't been able to reproduce this on my Win7 machine with cmake 3.0.0 or 3.5.0 and VS 2013
I've been using VS 2015 Update 2 on Windows 10, but I'll also try with VS 2013.

**Comment by huybui** [comment] 2017-01-20 22:12
I am using CMake 3.7.1.

**Comment by huybui** [comment] 2017-01-23 22:08
I tried with CMake 3.5.0 and there is no problem. So it must be an issue with CMake.

**Comment by redchillipadi** [comment] 2017-02-01 23:12
I am packaging Opensubdiv 3.1.1 for Gentoo linux and have the same issue with CMake >= 3.7.0.

What happens is that CMakeLists.txt sets a variable OPENSUBDIV_VERSION_STRING to "3.1.1" (i.e. the string contains the version number wrapped in double quotes).

Code generated by CMake's Modules/FindCUDA.cmake transforms this into an improperly quoted semicolon separated list:
set(CUDA_NVCC_COMPILE_DEFINITIONS "OPENSUBDIV_VERSION_STRING="3.x.x";OPENSUBDIV ... ")

This is then transformed into a command line to pass to nvcc to compile the osd static and dynamic gpu cuda kernels but the string has dangling quotes. The section shown above converts to:
-DOPENSUBDIV_VERSION_STRING -D3.1.1\";-DOPENSUBDIV...

The code to convert the definitions such as OPENSUBDIV_VERSION_STRING into CUDA_NVCC_COMPILE_DEFINITIONS was introduced to Modules/FindCUDA.cmake (commit 6442709b) which was merged into Cmake 3.7.0. Prior versions of FindCUDA set the flags for nvcc differently and are able to compile opensubdiv on my system. CMake 3.6.3 works for me, but 3.7.0 and 3.7.2 fail.

Ideally the FindCUDA.cmake code could be made more robust to handle definitions containing quotation marks. In any case removing the extra quotes from the OPENSUBDIV_VERSION_STRING (set it to 3.1.1 rather than "3.1.1") resolves the problem and allows opensubdiv to compile successfully with CMake 3.7.2.

```
diff -Naur a/CMakeLists.txt b/CMakeLists.txt
--- a/CMakeLists.txt	2017-02-01 23:20:22.590219192 +1100
+++ b/CMakeLists.txt	2017-02-01 23:19:59.923600152 +1100
@@ -48,7 +48,7 @@
     string(REGEX REPLACE "^v" "" OSD_SONAME ${OSD_SONAME})
 
     add_definitions(
-        -DOPENSUBDIV_VERSION_STRING="${OSD_SONAME}"
+        -DOPENSUBDIV_VERSION_STRING=${OSD_SONAME}
     )
 
 #-------------------------------------------------------------------------------
```

**Comment by davidgyu** [comment] 2017-02-01 23:33
Ah, that makes sense. Nice debugging. We'll take a look...

**Comment by renexdev** [comment] 2017-03-16 14:31
Hi there, thanks @redchillipadi for the trick it solved the the string issue!
 Nevertheless, in my case it gives me another error that may be its related to OPENSUBDIV_VERSION_STRING set variable. In the compilation step I got the following error when trying to build the samples...
I paste the output for glImaging sample...

[ 91%] Building CXX object examples/glImaging/CMakeFiles/glImaging.dir/glImaging.cpp.o
<command-line>:0:27: error: too many decimal points in number
$HOME/OpenSubdiv-master/examples/glPaintTest/glPaintTest.cpp:1108:65: note: in expansion of macro ‘OPENSUBDIV_VERSION_STRING’
     static const char windowTitle[] = "OpenSubdiv glPaintTest " OPENSUBDIV_VERSION_STRING;

The error spreads all over the samples with the same code-line. Any suggestion?
Thanks in advance

**Comment by redchillipadi** [comment] 2017-03-16 23:06
Expanding the variable from inside the quotes should work.
`static const char windowTitle[] = "OpenSubdiv glPaintTest ${OPENSUBDIV_VERSION_STRING}";`

**Comment by renexdev** [comment] 2017-03-17 19:39
Thanks it works!

**Comment by dracwyrm** [comment] 2017-09-30 09:05
The actual fix to this issue is attached at end of this post. There is no need for stringify or any of that. :) I'll create a PR in a bit so people can grab the patch easily, and hopefully upstream can merge it.
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index e02ce90c..6d4f5342 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -48,7 +48,7 @@ endif()
     string(REGEX REPLACE "^v" "" OSD_SONAME ${OSD_SONAME})
 
     add_definitions(
-        -DOPENSUBDIV_VERSION_STRING="${OSD_SONAME}"
+        -DOPENSUBDIV_VERSION_STRING=\\\"${OSD_SONAME}\\\"
     )
 
```

**Comment by dracwyrm** [comment] 2017-09-30 11:39
@jtran56 Hope this PR works for you. I think I signed the CLA thing for a different PR in a different program?

**Comment by jtran56** [comment] 2017-10-06 00:49
@dracwyrm Looks like we don't have a CLA from you yet in our records. If you could fill one out and email us as listed in the guidelines, then we can start to accept your pull requests. Thank you! https://github.com/PixarAnimationStudios/OpenSubdiv/blob/master/documentation/contributing.rst#contributor-license-agreement

**Comment by davidgyu** [comment] 2020-03-06 21:45
The underlying problem in FindCUDA.cmake has been fixed for the last several releases of CMake (tested back through CMake v3.9).

We're going to close this as not-fixing based on our recent testing of OpenSubdiv releases across multiple platforms Windows, Linux, macOS, etc, including VS 2013/2015/2017/2019 and CUDA 8, 9, 10 on Windows.

Thanks!

**Closed by davidgyu** 2020-03-06 21:45 UTC
