### ISSUE TITLE
Support dynamic linking on Windows?

### ISSUE THREAD

**Issue by oracle3001** [PixarAnimationStudios/OpenSubdiv#1000] opened 2018-09-28 00:11 UTC
Is there any chance that adding this functional is a possibility / on the roadmap?

**Comment by davidgyu** [comment] 2018-10-09 23:20
This isn't on our near term roadmap, but agree that it would be nice to have.

There is some work toward supporting this in the existing CMake scripts, but the main task here is updating the public classes to manage exported symbols, i.e. decorating classes methods, etc with appropriate dllimport/dllexport attributes.

**Comment by davidgyu** [comment] 2020-03-06 22:57
Marking as duplicate of #71

**Closed by davidgyu** 2020-03-06 22:57 UTC
