### ISSUE TITLE
glEvalLimit Example App Crash When Selecting Catmark_fan Shape

### ISSUE THREAD

**Issue by oracle3001** [PixarAnimationStudios/OpenSubdiv#921] opened 2017-01-18 13:36 UTC
I have found that when testing the glEvalLimit example, whenever I select the Catmark_fan shape, it causes the following error:

Program: C:\WINDOWS\SYSTEM32VCP140D.dll
File: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector
Expression: vector subscript out of range

This occurs no mater if I have compute set to CPU or GPU. I am using OpenSubDiv library (3.1.1) and example have been built in 32-bit with the following:

VS2015 (update 1) on Windows 10
glew-2.0.0
glfw-3.2
ptex (latest from git & built with VS2015)
zlib (latest from git & built with VS2015)
Cuda 8.0.44

Edit:- Should also be noted that I get the same issue with the glFFarViewer example, again only with the Catmark_fan shape.

**Comment by barfowl** [comment] 2017-01-18 19:19
Could you please verify that your build has the patch included for #915 is it was intended to address this case.  glEvalLimit appears to be working for me with gcc so I'll need to coordinate with someone for something specific to MSVC (thanks for the details above).

Incidentally, I think the glFVarViewer crash is a result of me revising that shape and omitting UVs -- the app crashes with any shape without UVs.

**Comment by oracle3001** [comment] 2017-01-19 11:17
My apologies I didn't see that this issue had been addressed in the dev branch. I have now cloned the dev branch and built from that and can confirm that this fixes the crashing within the glEvalLimit demo.

**Comment by jtran56** [comment] 2017-01-19 18:38
Filed as internal issue #142047.

**Comment by barfowl** [comment] 2017-01-19 23:03
Great, glad to hear this is no longer a problem.  You should also being seeing the fix in the master branch though -- not just dev -- as this was merged when 3.1.1 was created early last week.

Thanks for pointing out the glFVarViewer issue.  I'll close this issue for now and have opened #923 to deal with glFVarViewer.  I could just remove the revised shape or add UVs, but the app should be more robust.

**Closed** 2017-01-19 23:03 UTC
