### ISSUE TITLE
Errors when running glFVarViewer with latest dev branch

### ISSUE THREAD

**Issue by oracle3001** [PixarAnimationStudios/OpenSubdiv#1027] opened 2018-11-22 15:38 UTC
Building from the latest dev branch on Windows 10, using VS2018 (15.8.9), I get the follow set of errors when running glFVarViewer.

NVIDIA Corporation
GeForce GTX 960M/PCIe/SSE2
4.6.0 NVIDIA 416.94
Init OpenGL 4.6
Error: 4
Error linking GLSL program: Geometry info
-------------
0(1780) : error C5041: cannot locate suitable resource to bind variable "@wP.538-1425". Possibly large array.
0(1774) : error C5041: cannot locate suitable resource to bind variable "@wP16.546-1425". Possibly large array.
0(1781) : error C5041: cannot locate suitable resource to bind variable "@wDs.539-1425". Possibly large array.
0(1774) : error C5041: cannot locate suitable resource to bind variable "@wDs16.547-1425". Possibly large array.
0(1781) : error C5041: cannot locate suitable resource to bind variable "@wDt.540-1425". Possibly large array.
0(1774) : error C5041: cannot locate suitable resource to bind variable "@wDt16.548-1425". Possibly large array.
0(1782) : error C5041: cannot locate suitable resource to bind variable "@wDss.541-1425". Possibly large array.
0(1774) : error C5041: cannot locate suitable resource to bind variable "@wDss16.549-1425". Possibly large array.
0(1782) : error C5041: cannot locate suitable resource to bind variable "@wDst.542-1425". Possibly large array.
0(1774) : error C5041: cannot locate suitable resource to bind variable "@wDst16.550-1425". Possibly large array.

etc etc etc

**Comment by davidgyu** [comment] 2018-11-23 20:20
I can reproduce these errors on one of my NV systems but not on another:
errors:
  GeForce RTX 2080 Ti/PCIe/SSE2
  4.6.0 NVIDIA 416.94
  VS2017 15.8.9
no errors:
  GeForce GTX 750M/PCIe/SSE2
  4.6.0 398.82
  VS2017 15.8.9

I'll investigate further. Thanks! -David

**Comment by davidgyu** [comment] 2018-11-23 21:45
Updated the driver on my system with the 750M to 416.94 and now seeing the errors there as well (no other changes). So, these errors appear to be dependent on driver versions.

**Comment by jtran56** [comment] 2018-12-03 21:48
Filed as internal issue #OSD-247.

**Comment by barfowl** [comment] 2019-02-26 00:13
David's pull request #1055 on 2/05 was intended to address this.  Are you still experiencing this problem in the dev branch beyond that commit?  If not, we should be able to close this, thanks.

**Comment by oracle3001** [comment] 2019-02-26 09:59
I am still encountering this issue with the latest dev branch.

**Comment by c64kernal** [comment] 2019-03-02 08:06
I'm not getting these errors with the 418.96 drivers:

NVIDIA Corporation
GeForce GTX 1070 with Max-Q Design/PCIe/SSE2
4.6.0 NVIDIA 418.96

@oracle3001 any chance these errors are also fixed for you with the newer drivers?

**Comment by oracle3001** [comment] 2019-03-02 11:51
Unfortuanately, I am still having this issue running the very latest NVIDIA driver,

NVIDIA Corporation
GeForce GTX 960M/PCIe/SSE2
4.6.0 NVIDIA 419.17
Init OpenGL 4.6

**Comment by c64kernal** [comment] 2019-03-02 19:07
Okay, thanks for the update!

**Comment by poljere** [comment] 2019-03-05 00:25
One more data point, I was not able to repro this issue with the following configuration:

NVIDIA Corporation
GeForce GTX 1060/PCIe/SSE2
4.6.0 NVIDIA 419.17
Init OpenGL 4.6

**Comment by davidgyu** [comment] 2020-03-23 21:17
Marking this closed. We haven't been able to reproduce this after extensive testing using recent drivers on any systems including Windows 10 1809 / 1909 using VS 2017-15.9.21 / 2019-16.5.0 and others on Kepler/Maxwell/Pascal/Turing.

As mentioned by barfowl, the original manifestation of this bug was mitigated by the changes in #1055, but we have been unable to reproduce these errors on any of our test systems even with that PR backed out and using recent drivers.

Seems to have been some changes around the 41X series drivers, that has since been improved NVIDIA.

**Closed by davidgyu** 2020-03-23 21:17 UTC
