### ISSUE TITLE
X11, GLFW, and OSX oh my

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/OpenSubdiv#903] opened 2016-10-25 18:19 UTC
The detection of GLFW has got way too many places to look for macOS, and as a result can be led astray if you have an X11 install. Similarly to USD, OpenSubdiv should have a mechanism to opt out X11 on macOS.

Related, the regressions and examples require GLFW. Unfortunately there is no way to opt out of GLFW, and when you are in an X11 tangle...

You can bypass the regressions and examples like this -

-DNO_OPENGL=1
-DNO_REGRESSION=1

you'll get past the problem, but sadly you will also lose OpenGL everywhere.

I think that there should be a NO_X11 switch, and a NO_GFLW switch.

**Comment by jonogibbs** [comment] 2016-10-25 18:32
The problem which triggered this is on Ubuntu 14.04, I'm getting a bad linking order resulting in a unresolved symbol on things like glViewer and the OSD regression test. The issue is that "x11" is specified before "glfw", but "glfw" is needing to bring in symbols from "x11". I think glfw should safely be prior to any standard X libraries.

It would also be nice to have a "-DNO_GLFW=1" to opt out of any GLFW needing targets since I didn't actually need them. Specifying -DNO_OPENGL=1 does allow a build but you loose the osdGPU library.

**Comment by davidgyu** [comment] 2016-10-26 01:09
Yup, great points! I think your suggestion of NO_X11 and NO_GLFW options sounds good.

**Comment by davidgyu** [comment] 2017-09-26 20:22
Closed by #945

**Closed by davidgyu** 2017-09-26 20:22 UTC
