### ISSUE TITLE
ninja build broken on dev branch recently

### ISSUE THREAD

**Issue by nyue** [PixarAnimationStudios/OpenSubdiv#1268] opened 2022-09-13 01:23 UTC
Hi,

  I have been building the last couple of commits and noticed that while `make` works, ninja is no longer able to build.

  If the CI/CD uses make, it may not be able to pick up the errors.

```
$ ninja
ninja: warning: phony target 'documentation/search.html' names itself as an input; ignoring [-w phonycycle=warn]
ninja: warning: multiple rules generate documentation/search.html. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: error: dependency cycle: documentation/search.html -> documentation/CMakeFiles/search.html -> documentation/search.html
```

Cheers

**Comment by davidgyu** [comment] 2022-09-15 19:01
Filed as internal issue #OSD-387

**Comment by davidgyu** [comment] 2023-07-27 19:58
Duplicate of #1269

**Closed as not planned by davidgyu** 2023-07-27 19:58 UTC
