### ISSUE TITLE
VS2013 Build Errors - more than one [] operator for StackBuffer

### ISSUE THREAD

**Issue by thomthom** [PixarAnimationStudios/OpenSubdiv#622] opened 2015-06-10 10:35 UTC
I observe build errors in Visual Studio 2013 (OpenSubdiv 3.0.0 RC1).

CMake config to generate Vs solution:

```cmake
cmake ^
  -G "Visual Studio 12 2013" ^
  -DNO_EXAMPLES=1 ^
  -DNO_TUTORIALS=1 ^
  -DNO_REGRESSION=1 ^
  -DNO_MAYA=1 ^
  -DNO_PTEX=1 ^
  -DNO_DOC=1 ^
  -DNO_OMP=1 ^
  -DNO_TBB=1 ^
  -DNO_CUDA=1 ^
  -DNO_OPENCL=1 ^
  -DNO_OPENGL=1 ^
  -DNO_CLEW=1 ^
  ..
```

Full error list upon build: https://gist.github.com/thomthom/cfadd7d384d8b394aabb

![2015-06-10_11h46_50](https://cloud.githubusercontent.com/assets/192418/8080347/05ad9a46-0f6c-11e5-804d-88da034cad7d.png)

All the errors appear to be related to the same thing. Patterns like this:

```cpp
    internal::StackBuffer<Index,16> cVertEdgeBuffer;

    ConstIndexArray pVertEdges = _parentLevel.getVertexEdges(pVert);
    ConstIndexArray cVertEdges;

    //  Beware accessing the child's vert-edges -- full topology may not be enabled:
    if (_childLevel.getNumVertexEdgesTotal()) {
        cVertEdges = _childLevel.getVertexEdges(cVert);
    } else {
        cVertEdgeBuffer.SetSize(pVertEdges.size());

        ConstLocalIndexArray pVertInEdge = _parentLevel.getVertexEdgeLocalIndices(pVert);
        for (int i = 0; i < pVertEdges.size(); ++i) {
            cVertEdgeBuffer[i] = _refinement.getEdgeChildEdges(pVertEdges[i])[pVertInEdge[i]];
        }
        cVertEdges = IndexArray(cVertEdgeBuffer, pVertEdges.size());
    }
```

It's the `cVertEdgeBuffer[i]` that chokes - VS doesn't like `int` being passed to `[]` which signature accepts `unsigned int`.

If I made a `static_cast` of `i` then there'd be no error.

As a quick and dirty test I added an overload to `StackBuffer` and that allowed the build to complete with no errors:

```cpp
    TYPE &       operator[](int index)        { return _data[static_cast<size_type>(index)]; }
    TYPE const & operator[](int index) const  { return _data[static_cast<size_type>(index)]; }
```
![2015-06-10_12h21_08](https://cloud.githubusercontent.com/assets/192418/8080442/dc187f60-0f6c-11e5-8194-db3556825475.png)

I would submit a patch, but I'm not sure what the preferred fix would be. (Plus I saw that I need to sign that agreement before submitting contributions.)

**Comment by thomthom** [comment] 2015-06-10 12:42
```cpp
class ConstArray {

public:
    typedef TYPE value_type;
    typedef int  size_type;
```
...
```cpp
const_reference operator[](int index) const { return _begin[index]; }
```

I saw there was a comment that the size type was intentionally 32bit to avoid 64bit conversion - hence the `int`. But can it be `unsigned`?

**Comment by barfowl** [comment] 2015-06-10 17:30
I don't have access to MSVC but I'm told others are not having this problem
-- with earlier versions or with 2013.  This code is being instantiated in
a template on the client side though and is subject to whatever compiler
settings used there, which may be stricter.

I'm not opposed to changing the size to "int" though.  The issue may be
that we start to get more warnings from casts from unsigned to signed, but
most usage likely already uses signed.  It's used internally though so we
should be able to deal with that.

I'll look into it and don't mind making the change if that's fine with the
rest of the team.

**Comment by barfowl** [comment] 2015-06-10 17:53
Sorry, I misread your last email -- I was referring to changing
StackBuffer::size_type to signed not ConstArray::size_type to unsigned.

ConstArray is intended to directly return sizes that are internally 32-bit
signed and passed on as signed, so I would prefer not to change that.

**Comment by thomthom** [comment] 2015-06-10 18:04
So these people with VS2013, was their project configured to use the vs2013
compiler? Or did it use an older like vs2010?
I tried on two different systems now and both failed.




Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=6.3.35&pv=5.0.2]

On Wed, Jun 10, 2015 at 7:53 PM, barfowl < notifications@github.com [notifications@github.com] > wrote:
Sorry, I misread your last email -- I was referring to changing
StackBuffer::size_type to signed not ConstArray::size_type to unsigned.

ConstArray is intended to directly return sizes that are internally 32-bit
signed and passed on as signed, so I would prefer not to change that.


On Wed, Jun 10, 2015 at 10:30 AM, Barry Fowler <barry.fowler@dreamworks.com>
wrote:

> I don't have access to MSVC but I'm told others are not having this
> problem -- with earlier versions or with 2013. This code is being
> instantiated in a template on the client side though and is subject to
> whatever compiler settings used there, which may be stricter.
>
> I'm not opposed to changing the size to "int" though. The issue may be
> that we start to get more warnings from casts from unsigned to signed, but
> most usage likely already uses signed. It's used internally though so we
> should be able to deal with that.
>
> I'll look into it and don't mind making the change if that's fine with the
> rest of the team.
>
> On Wed, Jun 10, 2015 at 5:42 AM, Thomas Thomassen <
> notifications@github.com> wrote:
>
>> class ConstArray {
>> public:
>> typedef TYPE value_type;
>> typedef int size_type;
>>
>> ...
>>
>> const_reference operator[](int index) const { return _begin[index]; }
>>
>> I saw there was a comment that the size type was intentionally 32bit to
>> avoid 64bit conversion - hence the int. But can it be unsigned?
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
<https://github.com/PixarAnimationStudios/OpenSubdiv/issues/622#issuecomment-110734789>
>> .
>>
>
>
—
Reply to this email directly or view it on GitHub
[https://github.com/PixarAnimationStudios/OpenSubdiv/issues/622#issuecomment-110852774] .[https://github.com/notifications/beacon/AALvokS9y9QO98RSvwt78VoNPubPkxb-ks5oSHEbgaJpZM4E-RV8.gif]

**Comment by barfowl** [comment] 2015-06-10 18:13
A member of the team tried it on both VS2010 and VS2013 and couldn't
reproduce it.  I'll let him provide details.

Can you please verify that a sign change to StackBuffer resolves issue?  If
we change its size_type to signed there is a little more to be changed, but
changing the argument to operator[] to "int index" should suffice for
testing.

Thanks

On Wed, Jun 10, 2015 at 11:05 AM, Thomas Thomassen <notifications@github.com
> wrote:

> So these people with VS2013, was their project configured to use the vs2013
> compiler? Or did it use an older like vs2010?
> I tried on two different systems now and both failed.
>
>
>
>
> Sent using CloudMagic [
> https://cloudmagic.com/k/d/mailapp?ct=pa&cv=6.3.35&pv=5.0.2]
>
>
> On Wed, Jun 10, 2015 at 7:53 PM, barfowl < notifications@github.com [

**Comment by barfowl** [comment] 2015-06-10 18:23
Clearly I am not paying attention today -- you have already done that,
thanks.

I am curious as to why passing a signed index to an operator[] that accepts
unsigned would cause such a problem.  It must be common to pass a signed
index to std::vector's operator[], and std::vector's size_type is supposed
to be unsigned, so I am curious as to why that wouldn't trigger the same
problem -- perhaps the 32-bit signed to 64-bit unsigned conversion avoids
it.

**Comment by takahito-tejima** [comment] 2015-06-10 18:42
Hi, I could repro the error if I configure 32bit build in VS2013.

It seems like VC is trying to apply operator TYPE *() first then apply 
[] to the pointer, resulting ambiguous overloads.
But if I configure for 64bit binary it doesn't complain.

I'll continue the investigation.

thanks

**Comment by thomthom** [comment] 2015-06-10 21:43
Yes - the error message in the tooltip appear to give better info than the console output.
`built-in operator"pointer-to-object[integer]"` clashes with `operator[]`.

Btw - I must have missed something in my config of the VS solution as I only have Win32 as build option. Do I need to configure CMake for this - or is it simply enough to just add the x64 manually?

In my case I would need to build both architectures.

I'll poke around some more tomorrow.

**Comment by barfowl** [comment] 2015-06-11 05:26
We merged a change earlier into the dev branch (#625) that should take care of this.  Takahito exercised it on both 32- and 64-bit builds of VS2013 (and 2010 I believe).

Takahito was also closer to the mark of the source of the problem.  There is no [] that takes a signed int, but there are two "methods" that take an unsigned:  operator[unsigned] and operator TYPE*()[unsigned].  This isn't ambiguous in a 64-bit build since the former takes 32-bit unsigned and the latter 64-bit and one takes precedence.

We ended up getting rid of operator[] entirely to avoid any ambiguity and rely on the implicit casting to TYPE* followed by [].  This class was intended as a replacement for VLAs and alloca() so relying on the TYPE* operator and little else is more in the spirit of its intent.

Thanks for taking the time with this.  I'll wait for your confirmation before closing.

**Comment by thomthom** [comment] 2015-06-11 09:05
The dev branch builds successfully for Win32 on my machine. Thanks!

Wasn't able to test x64 - the VS solution didn't have the config set up. Is this something that should have been done by CMake? How do you generate a x64 config for the VS solution? (I've not used CMake before - I suspect I'm missing something obvious.)

**Comment by takahito-tejima** [comment] 2015-06-11 15:44
you can run cmake with -G "Visual Studio 12 Win64" and you'll get a x64 
config for VS2013.

**Comment by barfowl** [comment] 2015-06-11 17:21
Great, I'll close this then.  If there are any further issues related to VS configurations lets address those in a separate isssue.  Thanks again

**Closed by barfowl** 2015-06-11 17:21 UTC
