### ISSUE TITLE
Crash in MSCV Debug model with corner crease and CREASE_CHAIKIN

### ISSUE THREAD

**Issue by thomthom** [PixarAnimationStudios/OpenSubdiv#789] opened 2016-02-20 16:46 UTC
Yes - this is very specific - bear with me.

The crash happen under these conditions:
* Visual Studio 2013 compiler. Crash happen only in Debug mode - Release work fine.
* You have a creased vertex at the border of a mesh. Ie, not a solid manifold. Crease a vertex of a single quad.
* You have `CREASE_CHAIKIN` creasing mode.
* The Crease weight is less than or equal to the max refinement level. Crease weight higher than the refinement level works fine.

![image](https://cloud.githubusercontent.com/assets/192418/13197819/decef432-d7f8-11e5-9165-0071acda0460.png)

The crash occurs when `ComputeVertexVertexMask` returns. If you step through the code and use StepInto at the end it'll step into the destructor of `LocalMask` and `Crease` before it with crash inside the CRT (I think).

I created a gist with modified `far_tutorial0.cpp` which reproduce it as simple as I can manage: https://gist.github.com/thomthom/242aa26f8f469a05d5a5

I built OpenSubdiv using this Cmake config:

```
cmake ^
  -G "Visual Studio 12 2013 Win64" ^
  -D NO_REGRESSION=1 ^
  -D NO_MAYA=1 ^
  -D NO_PTEX=1 ^
  -D NO_DOC=1 ^
  -D NO_OMP=1 ^
  -D NO_TBB=1 ^
  -D NO_CUDA=1 ^
  -D NO_OPENCL=1 ^
  -D NO_OPENGL=1 ^
  -D NO_DX=1 ^
  -D NO_CLEW=1 ^
  ..
```

I don't know if this is an OSD bug or a MSVC Debug CRT bug - but I've reached as far as I can on this. I don't see an obvious cause or fix. But it's making it hard for me to debug my own application when some of my models keep crashing.

I am using the `dev` branch which is currently at a state where it just merged the 3.0.4 release - no other commits after that.

**Comment by barfowl** [comment] 2016-02-22 18:33
I'll have a look at this shortly since I am most familiar with that code.  I don't have access to MSVC but I'll see if there's anything suspicious with the Chaikin implementation in general.  There may be some corruption of the stack earlier on that is triggering this crash on return.

**Comment by thomthom** [comment] 2016-02-22 18:37
That's what I was wondering - bit strange that I only see this in Debug - but maybe that's just by chance so far. Maybe I see this in Debug because of how it handles memory differently and got more error checking.

**Comment by manuelk** [comment] 2016-02-22 23:11
probably an STL vector accessed out of bounds or un-initialized (we had to fix a number of those in Vtr for MSVC)

Incidentally, you can post simple .obj files if the crash is easily reproducible as it seems to be.

**Comment by barfowl** [comment] 2016-02-23 17:20
I have found a bug in the Chaikin creasing code, but it is one of those things you would expect to be breaking far more often than it is, not just in DEBUG mode.  Given the Chaikin creasing is rarely used and the case is fairly specific (a vertex transitioning from Corner to Crease with no semi-sharp edges present), perhaps that is not surprising.

I experience a similar crash with ICC in a test program of mine given the mesh you specified (single quad with smooth corners and one semi-sharp corner of 1.0), but again only in DEBUG.  The following change fixes the problem.

Change line 171 of sdc/crease.cpp from:

    171        childSharpness[i] = Crease::SHARPNESS_SMOOTH;
to
    171        childSharpness[i] = parentSharpness[i];

and let me know if that makes MSVC happy.  If so I'll start preparing a Pull Request..

**Comment by thomthom** [comment] 2016-02-23 17:54
Perfect! No crash. :)

I had picked Chaikin as default for my app - hence used pretty much for every model I was testing with.

**Comment by barfowl** [comment] 2016-02-23 18:22
Great, thanks.  It sounds like you've probably done more testing of Chaikin than anyone else then.  I was beginning to suspect more of that code when this bug was discovered, but it sounds like you will have exercised it well.

I noticed your test mesh also had the TRI_SUB_CATMARK option set.  Is that your choice of default too?

I'm speaking for myself here (curious what the rest of the team thinks), but I don't recommend making Chaikin or the TriSubCatmark options your default.  Both are really special purpose features that were rarely used in all of the years that RenderMan exposed them.  As a result, most other subdiv modeling tools will not likely make them the default, so consistency is something to consider for your users.

You will also pay added overhead during the refinement stage with Chaikin turned on, when it has dubious benefit.  It does sometimes improve the shape, but it does not do as good a job of what it strives to do.  I would recommend only turning it on when it provides noticeable benefit.  There was some talk of trying to come up with another non-uniform creasing scheme that did a better job than Chaikin, but there are so many other more important issues to address first.

**Comment by manuelk** [comment] 2016-02-23 20:03
TRI_SUB_CATMARK: these are the "original" weights and what most non-OSD applications probably use. IIRC, the "smooth triangle" rules were added later (2005 ish maybe ?) to Renderman and turned into the default setting. Since Maya / MAX now use OSD, i assume that the smooth rule is the default too, until they have to revert to their legacy code for non-manifold meshes. Julian would know more on the Renderman side and "other implementations may vary"...

**Comment by barfowl** [comment] 2016-02-23 20:12
Thanks, my mistake -- the "CATMARK" in the name means use the standard Catmull-Clark rules in the presence of triangles, which most will be doing.  Forget I even brought the subject up...

**Comment by thomthom** [comment] 2016-02-23 22:18
The `TRI_SUB_CATMARK` option in my snipped wasn't actually relevant for this bug. I just added them all in there as I was fiddling back and forth trying to repro the crash.

It's an interesting point you bring up though. I noticed Chaikin wasn't enabled by default and I have been going back and forth on this.
So a little background on my project. I originally has my own implementation of Catmull-Clark along with creasing. Based on different info from different sources. Then I realized there was this library - which is the de-factor standard - so I'm now replacing my own  implementation with OSD.

In my own implementation I actually had Chaikin enabled at all time. There was no way to disable it. So that's why I've had it turned on be default - for now. (I'm still in development mode for the OSD refactor.) Most models looks mostly the same when I use matching settings - so I have to figure out what makes sense - keeping defaults compatible with my older version or keep defaults aligned with other packages. (I'm somewhat leaning towards the latter.)

As for performance, it won't be much for an issue for me right now. I'm working on a plugin for an API that doesn't expose access to the viewport - so there is no real-time subdivision going on. I take an input mesh and replace it with a subdivided output mesh. Having to regenerate the mesh within the model DOM is way more expensive than whatever Chaikin might do to performance.

Back to Chaikin - default or not - I have noticed that it isn't always ideal. So you might have swayed me to turn it off by default. :) It's good to hear feedback.

As for the triangle subdivision options, do I understand it correctly that `TRI_SUB_CATMARK` is the default in other software packages? 
Is the defaults in OSD source mostly what implementation defaults are as well?

Anyway - I digress. Thank you so much for looking into this. I appreciate it. Let me know if I can assist in any way.

**Comment by barfowl** [comment] 2016-02-23 23:07
Let's put the TRI_SUB_CATMARK issue behind us -- yes, it is the default for OpenSubdiv and should be the default in most packages (since the other choice is not standard Catmull-Clark subdivision).  Since you were setting it explicitly in the code you provided, I assumed you were overriding the default as I had forgotten what the option names meant.

Manuel, recall the discussion we had with Autodesk (about 15 months ago now) and you spoke to Julian to dig up the Renderman history...  The Renderman docs are incorrect -- the "smooth triangle" option was never made the default in Renderman and it was in fact obscure to set it explicitly given another option that was never enabled in the code.  Autodesk had enabled the smooth triangle option by default, and favored its usage (it does produce better shapes) but agreed it was best to revert back to standard Catmull-Clark rules for the sake of consistency with other packages.

Back to Chaikin, Thomas, I can see now why you favor making it the default.  Regarding the history of Chaikin elsewhere -- notably Renderman -- it was never completely implemented in Renderman until after OSD's release.  It was pointed out that the feature was not fully enabled in the code shared between OSD and Renderman and was then corrected first in OSD and later in a more recent release of Renderman.  The point here is that it has had little practical use.

I agree that the performance aspects are probably negligible.  You should only notice a difference between Chaikin and Uniform creasing when multiple different semi-sharp values (so excluding smooth and infinitely sharp values) exist around a vertex.  Chaikin should behave exactly the same as Uniform in all other cases (including your test case).  Most practical applications of the creasing uses edge loops of constant sharpness -- anything else can be tricky to make look good, even with Chaikin -- and the two methods should be identical in these cases.

Given your experience with your own implementation of the Chaikin creasing, if you do spot any unusual differences with OSD, definitely let me know.  Thanks

**Comment by thomthom** [comment] 2016-02-24 12:03
> Most practical applications of the creasing uses edge loops of constant sharpness -- anything else can be tricky to make look good, even with Chaikin -- and the two methods should be identical in these cases.
That's what I found as well - I don't think I ever felt the need to make non-uniform creases. And since uniform creases resulted in the same I left Chaikin on. I'm still tempted at leaving it off and match the default of other packages as I find that to be rather important.

> Given your experience with your own implementation of the Chaikin creasing, if you do spot any unusual differences with OSD, definitely let me know. Thanks
My impression was that the OSD version was smoother than my own. I had more jaggedness near the vertices - so my weights where probably not right.

**Comment by manuelk** [comment] 2016-02-24 16:53
Barry : indeed - i had forgotten about that double-snarl in prman. Best to let that dragon sleep again...

Thomthom : if you have a build of the glViewer, Barry added the catmark_chaikin(0/1) shapes that are probably one of the best demonstration of what the rules can do. It does make crease transitions a lot smoother, but unfortunately the remaining lumpiness still prevent this from becoming a practical modelling feature ; at least according to the modellers i spoke to.

**Comment by thomthom** [comment] 2016-02-24 17:28
Thank you very much for your feedback. I got additional questions on this subject, but I started a thread on the forums where we can take this (if you got time to entertain me): https://groups.google.com/forum/#!topic/opensubdiv/weziSi5QkUY

(Btw, the way the forum is embedded on the OSD site makes it rather difficult to link to threads.)

**Comment by manuelk** [comment] 2016-02-24 19:47
Forum embeds : sorry - didn't have the time to figure out how to get a ReST link to open in a new tab. I am sure there is a way... otherwise, it shouldn't be too hard to add some custom CSS for that page. Not a high priority though.

**Comment by thomthom** [comment] 2016-03-30 21:55
@barfowl The fix for this didn't make it for 3.0.5? Should I create a PR with the line that fixes it?

**Comment by barfowl** [comment] 2016-03-30 22:14
Correct, it didn't make it.  Sorry about that -- its purely my fault.  I was getting the PR ready a while ago and got distracted and wasn't in touch with the rest of the team about the 3.0.5 release.  I've got some time freeing up and will try to get that out later today.  If not, I may take you up on your offer...

**Comment by thomthom** [comment] 2016-03-30 22:18
Ok - thanks. No worries, I fully understand. And it haven't been blocking me either because I'm not scheduled to release in the immediate future. Just wanted to check in on who'd suppose to check it in. Appreciate the help.

**Comment by davidgyu** [comment] 2016-06-24 00:36
Fixed by https://github.com/PixarAnimationStudios/OpenSubdiv/pull/798

**Closed by davidgyu** 2016-06-24 00:36 UTC
