### ISSUE TITLE
Building OpenSubdiv as a dynamic library?

### ISSUE THREAD

**Issue by oracle3001** [PixarAnimationStudios/OpenSubdiv#1122] opened 2019-06-12 19:39 UTC
Just wondering if it is possible to build OpenSubDiv as a dynamic library (.DLL) / shared object (.SO). I wish to use OpenSubDiv with another library, which only allows interaction with a third party library via calling a load command for a dll.

**Comment by c64kernal** [comment] 2019-06-12 20:56
No, unfortunately that's not something that OpenSubdiv supports at the moment -- only static libraries on Windows if I'm not mistaken.  Shared objects are supported on the other platforms. Perhaps you can wrap the functionality you need into your own dll that you statically link against OpenSubdiv?

**Comment by jilliene** [comment] 2019-06-18 17:54
Filed as internal issue #OSD-293

**Comment by davidgyu** [comment] 2020-03-06 22:58
Marking as duplicate of #71

**Closed by davidgyu** 2020-03-06 22:58 UTC
